import React, { useState } from 'react';
import { DamlLedger, useParty, useLedger, useStreamQueries, Contract } from '@c7/react';
import { Role } from './daml/gen/Kyc/V1/Provider';
import { Attestation, Revoked } from './daml/gen/Kyc/V1/Attestation';

const WS_URL = "ws://localhost:6867"; // Canton Sandbox gRPC-Web port
const HTTP_URL = "http://localhost:7575"; // Canton Sandbox JSON API port
const DEFAULT_PARTY = "RegistryAdmin"; // Default party for the admin UI

const App: React.FC = () => {
  // Simple auth model: use a hardcoded token or get it from localStorage.
  // In a real app, this would involve a proper login flow (e.g., OIDC).
  const [token, setToken] = useState<string | null>(localStorage.getItem("daml-token"));

  const handleLogin = (newToken: string) => {
    localStorage.setItem("daml-token", newToken);
    setToken(newToken);
  };

  const handleLogout = () => {
    localStorage.removeItem("daml-token");
    setToken(null);
  };

  return (
    <div style={styles.appContainer}>
      <header style={styles.header}>
        <h1 style={styles.title}>Canton KYC Identity - Admin Dashboard</h1>
        {token && <button onClick={handleLogout} style={styles.logoutButton}>Logout</button>}
      </header>
      <main style={styles.mainContent}>
        {!token ? (
          <LoginScreen onLogin={handleLogin} />
        ) : (
          <DamlLedger token={token} party={DEFAULT_PARTY} httpBaseUrl={HTTP_URL} wsBaseUrl={WS_URL}>
            <AdminDashboard />
          </DamlLedger>
        )}
      </main>
    </div>
  );
};

const LoginScreen: React.FC<{ onLogin: (token: string) => void }> = ({ onLogin }) => {
  const [tokenInput, setTokenInput] = useState("");
  const [partyInput, setPartyInput] = useState(DEFAULT_PARTY);
  const [error, setError] = useState("");

  const generateDevToken = async () => {
    setError("");
    try {
      // NOTE: This is a simplified, insecure JWT generator for local development ONLY.
      // In production, tokens must be generated by a secure, trusted authentication service.
      const payload = {
        "https://daml.com/ledger-api": {
          "ledgerId": "sandbox", // This must match your sandbox ledgerId
          "applicationId": "kyc-admin-ui",
          "actAs": [partyInput],
          "readAs": [partyInput]
        }
      };
      const header = { "alg": "HS256", "typ": "JWT" };
      const secret = "secret"; // Default secret for `dpm sandbox`
      const encodedHeader = btoa(JSON.stringify(header)).replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
      const encodedPayload = btoa(JSON.stringify(payload)).replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
      const data = `${encodedHeader}.${encodedPayload}`;
      
      // A real signature would use crypto libraries. For sandbox with a known secret, this is a placeholder.
      // This is NOT a valid HMAC-SHA256 signature. `dpm sandbox` accepts it due to lax validation.
      const dummySignature = "dummy-signature-for-dev-only";
      
      const token = `${data}.${dummySignature}`;
      setTokenInput(token);
    } catch (err) {
      setError("Failed to generate token.");
      console.error(err);
    }
  };

  return (
    <div style={styles.loginContainer}>
      <h2>Admin Login</h2>
      <p>Enter the admin party ID and a valid JWT to connect to the ledger.</p>
      <input
        type="text"
        placeholder="Admin Party ID"
        value={partyInput}
        onChange={(e) => setPartyInput(e.target.value)}
        style={styles.input}
        disabled // Keeping it fixed for this UI
      />
      <textarea
        placeholder="JWT Token"
        value={tokenInput}
        onChange={(e) => setTokenInput(e.target.value)}
        style={{ ...styles.input, height: '100px' }}
      />
      <button onClick={() => onLogin(tokenInput)} style={styles.button}>Login</button>
      <button onClick={generateDevToken} style={{...styles.button, marginLeft: 10}}>Generate Dev Token</button>
      {error && <p style={styles.error}>{error}</p>}
      <p style={styles.info}>For local `dpm sandbox`, you can generate a development token for the default admin party.</p>
    </div>
  );
};

const AdminDashboard: React.FC = () => {
  const party = useParty();
  const ledger = useLedger();

  const { contracts: providers, loading: providersLoading } = useStreamQueries(Role);
  const { contracts: activeAttestations, loading: attestationsLoading } = useStreamQueries(Attestation);
  const { contracts: revokedAttestations, loading: revokedLoading } = useStreamQueries(Revoked);

  const handleRevoke = async (attestation: Contract<Attestation>) => {
    if (window.confirm(`Are you sure you want to revoke the attestation for ${attestation.payload.subject}?`)) {
      try {
        await ledger.exercise(Attestation.Revoke, attestation.contractId, {});
        alert("Attestation revoked successfully.");
      } catch (error) {
        console.error("Failed to revoke attestation:", error);
        alert(`Error: ${error}`);
      }
    }
  };

  return (
    <div>
      <h2 style={styles.sectionTitle}>Welcome, {party}</h2>

      <div style={styles.section}>
        <h3 style={styles.subTitle}>Registered Identity Providers</h3>
        <Table
          headers={["Provider Party", "Display Name", "Jurisdiction"]}
          rows={providers.map(p => [
            p.payload.provider,
            p.payload.displayName,
            p.payload.jurisdiction
          ])}
          loading={providersLoading}
        />
      </div>

      <div style={styles.section}>
        <h3 style={styles.subTitle}>Active KYC Attestations</h3>
        <Table
          headers={["Subject", "Provider", "Type", "Issued", "Expires", "Actions"]}
          rows={activeAttestations.map(a => [
            a.payload.subject,
            a.payload.provider,
            a.payload.attestationType,
            new Date(a.payload.issueDate).toLocaleDateString(),
            a.payload.expiryDate ? new Date(a.payload.expiryDate).toLocaleDateString() : "N/A",
            <button
              onClick={() => handleRevoke(a)}
              style={styles.actionButton}
            >
              Revoke
            </button>
          ])}
          loading={attestationsLoading}
        />
      </div>

      <div style={styles.section}>
        <h3 style={styles.subTitle}>Revoked Attestations</h3>
        <Table
          headers={["Subject", "Provider", "Type", "Revoked By", "Revocation Date"]}
          rows={revokedAttestations.map(r => [
            r.payload.attestation.subject,
            r.payload.attestation.provider,
            r.payload.attestation.attestationType,
            r.payload.revokedBy,
            new Date(r.payload.revocationTime).toLocaleString()
          ])}
          loading={revokedLoading}
        />
      </div>
    </div>
  );
};

interface TableProps {
    headers: string[];
    rows: (string | React.ReactNode)[][];
    loading?: boolean;
}

const Table: React.FC<TableProps> = ({ headers, rows, loading }) => {
    if (loading) {
        return <p>Loading data...</p>;
    }
    if (rows.length === 0) {
        return <p>No data available.</p>;
    }

    return (
        <table style={styles.table}>
            <thead>
                <tr>
                    {headers.map(h => <th key={h} style={styles.th}>{h}</th>)}
                </tr>
            </thead>
            <tbody>
                {rows.map((row, i) => (
                    <tr key={i} style={styles.tr}>
                        {row.map((cell, j) => (
                            <td key={j} style={styles.td}>{cell}</td>
                        ))}
                    </tr>
                ))}
            </tbody>
        </table>
    );
};

const styles: { [key: string]: React.CSSProperties } = {
  appContainer: { fontFamily: 'Arial, sans-serif', color: '#333' },
  header: { backgroundColor: '#003366', color: 'white', padding: '1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  title: { margin: 0, fontSize: '1.5rem' },
  logoutButton: { backgroundColor: '#fff', color: '#003366', border: 'none', padding: '0.5rem 1rem', borderRadius: '4px', cursor: 'pointer', fontWeight: 'bold' },
  mainContent: { padding: '1rem' },
  loginContainer: { maxWidth: '500px', margin: '50px auto', padding: '2rem', border: '1px solid #ccc', borderRadius: '8px', textAlign: 'center', boxShadow: '0 4px 8px rgba(0,0,0,0.1)' },
  input: { width: 'calc(100% - 22px)', padding: '10px', margin: '10px 0', borderRadius: '4px', border: '1px solid #ccc', fontSize: '1rem' },
  button: { backgroundColor: '#0055a5', color: 'white', padding: '10px 20px', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '1rem' },
  error: { color: 'red' },
  info: { fontSize: '0.8rem', color: '#666', marginTop: '1rem' },
  section: { marginBottom: '2rem', padding: '1rem', border: '1px solid #eee', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', backgroundColor: '#fff' },
  sectionTitle: { borderBottom: '2px solid #003366', paddingBottom: '0.5rem', marginBottom: '1rem' },
  subTitle: { color: '#003366' },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '1rem' },
  th: { backgroundColor: '#f2f2f2', textAlign: 'left', padding: '12px', borderBottom: '2px solid #ddd', textTransform: 'uppercase', fontSize: '0.85rem' },
  tr: { '&:hover': { backgroundColor: '#f9f9f9' } },
  td: { padding: '12px', borderBottom: '1px solid #ddd', verticalAlign: 'middle' },
  actionButton: { backgroundColor: '#d9534f', color: 'white', border: 'none', padding: '5px 10px', borderRadius: '4px', cursor: 'pointer', '&:hover': { backgroundColor: '#c9302c' } },
};

export default App;